env: "local"

storage_path: "./storage/storage.db"

http_server:
  address: "localhost:8082"
  timeout: 4s #время на чтение запроса и такое же на отправку
  idle-timeout: 60s #время жизни соединения с клиентом

